import Head from 'next/head'
import Link from 'next/link';
import styles from '@/styles/Home.module.css'

import { ErrorTrigger } from "@/components/error-trigger";

export default function Home() {
  return (
    <>
      <ErrorTrigger />
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header with About Us link */}
      <header style={{ width: '100%', padding: '1rem 0', textAlign: 'center', background: '#fafafa', borderBottom: '1px solid #eee' }}>
        <nav>
          <Link href="/about" legacyBehavior>
            <a style={{ fontWeight: 'bold', color: '#0070f3', textDecoration: 'none', fontSize: '1.1rem' }}>About Us</a>
          </Link>
        </nav>
      </header>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
        </div>

        <div className={styles.center}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://nextjs.org/learn"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>
    </>
  )
}